version: '3.9'
services:
    # Application
    bus-app:
        container_name: bus-app
        build:
          args:
            user: selim
            uid: 1000
          context: .
          dockerfile: ./docker/bus-app.dockerfile
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - bus-db
    # Web Server
    bus-web:
        container_name: bus-web
        build:
            context: .
            dockerfile: ./docker/bus-web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - bus-app
        ports:
            - 80:80
    # Database
    bus-db:
        image: mysql:8.0
        container_name: bus-db
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_USERNAME}
        ports:
            - 3306:3306
        restart: unless-stopped

volumes:
    dbdata:
